---
layout: cv
title: Daniel Arias Ocampo
---
# Daniel Arias Ocampo
Business Analyst

<div id="webaddress">
<a href="danieliariasocampo@gmail.com">isaac@applesdofall.org</a>
| <a href="http://en.wikipedia.org/wiki/Daniel_Arias">My wikipedia page</a>
</div>


## Personal Statement

I am a trilingual student in Spanish, Tagalog, and English. My professional experience includes Marketing; Financial 
Analysis; Project Management; and Business Analytics. Strong leadership skills. Collaborator who coordinates 
individual strengths to deliver a solid product. Knowledge and experience with Analytics Programs. 

## Education

__Bachelor in Business Analytics__

## Experience

__Data Engineer__                                          (April 2024- July 2024)
Extensiv                                                               Sandy, Utah

• Developed and maintained 10+ interactive dashboards to visualize key performance indicators for a third-party 
logistics (3PL) company, enhancing decision-making processes and operational efficiency. 

• Contributed to the optimization of data collection and storage processes, reducing data retrieval times, and 
improving system performance.

• Performed detailed analysis of large datasets to identify trends, anomalies, and opportunities for process 
improvements within the logistics domain.

__Course Analyst__                                     (April 2022- December 2022)
BYU-Idaho                                                           Rexburg, Idaho

• Analyzed quantitative and qualitative data from student assessments, surveys, and course evaluations, producing 10+ actionable reports a week to guide evidence-based decision-making. 

• Conducted 8+ detailed course audits daily to ensure clearness and accuracy of material causing improvement in 10+ courses. 

• Utilized weekly data-driven insights to recommend modifications to course structures, assessments, and 
activities, enhancing engagement and student performance. 

__Personal Finance Teacher Assistant__                   (January 2023-July 2024)
BYU-Idaho                                                           Rexburg, Idaho

• Analyzed quantitative and qualitative data from student assessments, surveys, and course evaluations, producing 10+ actionable reports a week to guide evidence-based decision-making. 

• Conducted 8+ detailed course audits daily to ensure clearness and accuracy of material causing improvement in 10+ courses. 

• Utilized weekly data-driven insights to recommend modifications to course structures, assessments, and 
activities, enhancing engagement and student performance. 

## Volunteer Experience

__Full-Time Representative__                              (March 2019- April 2020)
The Church of Jesus Christ of Latter-Day Saints           Quezon City, Philippines

• Monitored and lead groups of 15-20 volunteers to ensure quality control deriving in a better and more clear understanding about the purpose of the volunteering experience. 

• Completed 60+ work hours a week with people from varied backgrounds and cultures, helping to develop 
teamwork. 

## Skills

• SQL, ALTERYX, Tableau, Power BI, Python, Meticulous. 

• Strong analytical skills with the ability to collect, organize, analyze, and disseminate significant amounts of 
information with diligence and accuracy

• Strong Pyhton and R Studio Analytical Skills



<!-- ### Footer

Last updated: May 2013 -->